# backend/sample_data.py
import os

def generate_sample_23andme():
    """Generate sample 23andMe format data for testing"""
    sample_data = """# This data file generated by 23andMe.
# This data is for demonstration purposes only.
rsid	chromosome	position	genotype
rs1815739	11	66300000	CC
rs7495174	15	28000000	GG
rs9939609	16	53800000	TT
rs12722495	1	11710187	CC
rs2180341	1	11710943	GG
rs11568820	1	11711128	GG
rs4988235	2	136608646	AA
rs182549	2	136610054	CC
rs1726866	2	136613789	TT
rs1726866	2	136613789	TT
rs4680	7	150484989	GG
rs12913832	15	28365618	AA
rs1805007	16	89918846	CC
rs1805008	16	89918884	TT
rs1805009	16	89918943	GG"""
    
    return sample_data

def create_sample_file(filename="sample_23andme.txt"):
    """Create a sample 23andMe file for testing"""
    sample_content = generate_sample_23andme()
    
    with open(filename, 'w') as f:
        f.write(sample_content)
    
    print(f"Sample file created: {filename}")
    print("You can now upload this file to test the application.")
    return filename

if __name__ == "__main__":
    create_sample_file()
